const cropData = {
    teff: ["red teff", "white teff", "sergegna teff"],
    maize: ["white maize", "yellow maize"],
    wheat: ["durum wheat", "bread wheat"],
    barley: ["malt barley", "food barley"],
    sorghum: ["white sorghum", "red sorghum"],
    millet: ["finger millet", "pearl millet"],
    oats: ["common oats"],
    finger_millet: ["red finger millet", "brown finger millet"],
    triticale: ["common triticale"],
    rice: ["upland rice", "lowland rice"],
    chickpea: ["desi chickpea", "kabuli chickpea"],
    haricot_bean: ["red haricot", "white haricot"],
    lentil: ["red lentil", "green lentil"],
    faba_bean: ["small faba", "large faba"],
    pea: ["field pea", "garden pea"],
    grass_pea: ["common grass pea"],
    soybean: ["common soybean"],
    niger_seed: ["black niger", "yellow niger"],
    flaxseed: ["brown flaxseed", "golden flaxseed"],
    sesame: ["white sesame", "black sesame"],
    groundnut: ["red groundnut", "white groundnut"],
    sunflower: ["common sunflower"],
    potato: ["red potato", "white potato"],
    sweet_potato: ["orange sweet potato", "white sweet potato"],
    taro: ["common taro"],
    cassava: ["bitter cassava", "sweet cassava"],
    yam: ["white yam", "yellow yam"],
    enset: ["common enset"],
    onion: ["red onion", "white onion"],
    tomato: ["roma tomato", "cherry tomato"],
    cabbage: ["green cabbage", "red cabbage"],
    carrot: ["orange carrot", "purple carrot"],
    beetroot: ["red beetroot"],
    kale: ["curly kale", "lacinato kale"],
    lettuce: ["romaine lettuce", "iceberg lettuce"],
    spinach: ["flat-leaf spinach", "savoy spinach"],
    green_pepper: ["bell pepper", "jalapeno"],
    eggplant: ["long eggplant", "round eggplant"],
    okra: ["green okra"],
    squash: ["butternut squash", "acorn squash"],
    avocado: ["hass avocado", "fuerte avocado"],
    banana: ["cavendish banana", "plantain"],
    mango: ["kent mango", "keitt mango"],
    papaya: ["solo papaya", "maradol papaya"],
    orange: ["navel orange", "valencia orange"],
    lemon: ["eureka lemon", "lisbon lemon"],
    lime: ["persian lime", "key lime"],
    grapefruit: ["ruby red grapefruit", "white grapefruit"],
    pineapple: ["cayenne pineapple"],
    guava: ["white guava", "pink guava"],
    chilli_pepper: ["red chilli", "green chilli"],
    ginger: ["common ginger"],
    turmeric: ["yellow turmeric"],
    garlic: ["hardneck garlic", "softneck garlic"],
    fenugreek: ["common fenugreek"],
    coriander: ["common coriander"],
    coffee: ["arabica coffee", "robusta coffee"],
    tea: ["black tea", "green tea"],
    sugarcane: ["common sugarcane"],
    tobacco: ["virginia tobacco", "burley tobacco"],
    cotton: ["upland cotton", "pima cotton"],
    cut_flowers: ["rose", "lily"]
  };
  
  const validMarkets = ["Local", "Export"];
  
  module.exports = { cropData, validMarkets };